FROM php:7.4-fpm-alpine

ARG user=hans
ARG uid=1000

RUN apk update && apk add --no-cache --virtual \
    git \
    curl \
    zip \
    unzip \
    nodejs \
    npm \
    oniguruma-dev \
    libxml2-dev \
    libpng-dev


# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

#Create system user
RUN addgroup -g "$uid" -S "$user"
RUN adduser -G www-data $user -D -u $uid -h /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

# Set working directory
WORKDIR /var/www


USER $user

#di production panggil package terus hapus
#di development panggil package terus hapus
#lalu masukan ke github setelah itu jika di jalankan docker-compose run
#maka selesai